version: "3"
services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
  db:
    image: "postgres:11"
    container_name: "postgres"
    ports:
      - "54320:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - EDITOR=vim
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  my_dbdata: